### ISSUE TITLE
docker autofc2 ffmpeg error

### ISSUE THREAD

**Issue by Zhen-Bo** [HoloArchivists/fc2-live-dl#24]
I'm using 
`docker run -d --name autofc2 -v D:/Downloads/_FC2/autofc2.json:/app/autofc2.json:ro -v D:/Downloads/_FC2/recordings:/recordings ghcr.io/holoarchivists/fc2-live-dl:latest autofc2 --config /app/autofc2.json`
after the live stream offline
and I got this:

Task exception was never retrieved

future: <Task finished name='Task-14' coro=<AutoFC2.handle_channel() done, defined at /app/.local/lib/python3.10/site-packages/fc2_live_dl/autofc2.py:90> exception=FileNotFoundError(2, 'No such file or directory')>

Traceback (most recent call last):

  File "/app/.local/lib/python3.10/site-packages/fc2_live_dl/autofc2.py", line 93, in handle_channel

    await fc2.download(channel_id)

  File "/app/.local/lib/python3.10/site-packages/fc2_live_dl/FC2LiveDL.py", line 214, in download

    await self._remux_stream(fname_stream, fname_muxed)

  File "/app/.local/lib/python3.10/site-packages/fc2_live_dl/FC2LiveDL.py", line 279, in _remux_stream

    async with FFMpeg(mux_flags) as mux:

  File "/app/.local/lib/python3.10/site-packages/fc2_live_dl/ffmpeg.py", line 16, in __aenter__

    self._ffmpeg = await asyncio.create_subprocess_exec(

  File "/usr/local/lib/python3.10/asyncio/subprocess.py", line 218, in create_subprocess_exec

    transport, protocol = await loop.subprocess_exec(

  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1667, in subprocess_exec

    transport = await self._make_subprocess_transport(

  File "/usr/local/lib/python3.10/asyncio/unix_events.py", line 207, in _make_subprocess_transport

    transp = _UnixSubprocessTransport(self, protocol, args, shell,

  File "/usr/local/lib/python3.10/asyncio/base_subprocess.py", line 36, in __init__

    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,

  File "/usr/local/lib/python3.10/asyncio/unix_events.py", line 799, in _start

    self._proc = subprocess.Popen(

  File "/usr/local/lib/python3.10/subprocess.py", line 966, in __init__

    self._execute_child(args, executable, preexec_fn, close_fds,

  File "/usr/local/lib/python3.10/subprocess.py", line 1842, in _execute_child

    raise child_exception_type(errno_num, err_msg, err_filename)

FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg'

**Comment by hizkifw** [comment]
Thanks for the report. I forgot to install `ffmpeg` in the container. I pushed a commit, can you try to `docker pull ghcr.io/holoarchivists/fc2-live-dl:latest` and run the command again?

**Comment by Zhen-Bo** [comment]
waiting for another stream offline
btw:Is it normal that docker autofc2 wont see the preview file in the recordings folder?

**Comment by hizkifw** [comment]
You should see the recordings in the folder. Make sure you set the `outtmpl` in your config to point to `/recordings` as the output folder.

If you didn't, you can try to browse the container and see where the files are: `docker exec -it <container id> /bin/sh`. You can get the container id with `docker ps`.

**Comment by Zhen-Bo** [comment]
> 

Thanks a lot
The docker autofc2 should work functionally
`<m(__)m>`
