### ISSUE TITLE
how to fix this

### ISSUE THREAD

**Issue by erungeis** [HoloArchivists/fc2-live-dl#29]
```
C:\Users\ROG>fc2-live-dl https://live.fc2.com/87864958/
2022-07-23 15:37:48 [main] fc2-live-dl v2.1.1 [0m[K
2022-07-23 15:37:48 [fc2 87864958] Fetching stream info [0m[K
2022-07-23 15:37:50 [fc2 87864958] Found websocket url [0m[K
2022-07-23 15:37:52 [33m[fc2 87864958] Requested quality ('3Mbps', 'mid') is not available, waiting (1/15s) [0m[K
2022-07-23 15:37:53 [33m[fc2 87864958] Requested quality ('3Mbps', 'mid') is not available, waiting (2/15s) [0m[K
2022-07-23 15:37:54 [33m[fc2 87864958] Requested quality ('3Mbps', 'mid') is not available, waiting (3/15s) [0m[K
2022-07-23 15:37:55 [33m[fc2 87864958] Requested quality ('3Mbps', 'mid') is not available, waiting (4/15s) [0m[K
2022-07-23 15:37:57 [33m[fc2 87864958] Requested quality ('3Mbps', 'mid') is not available, waiting (6/15s) [0m[K
2022-07-23 15:37:58 [33m[fc2 87864958] Requested quality ('3Mbps', 'mid') is not available, waiting (7/15s) [0m[K
2022-07-23 15:37:59 [33m[fc2 87864958] Requested quality ('3Mbps', 'mid') is not available, waiting (8/15s) [0m[K
2022-07-23 15:38:00 [33m[fc2 87864958] Requested quality ('3Mbps', 'mid') is not available, waiting (10/15s) [0m[K
2022-07-23 15:38:02 [33m[fc2 87864958] Requested quality ('3Mbps', 'mid') is not available, waiting (11/15s) [0m[K
2022-07-23 15:38:03 [33m[fc2 87864958] Requested quality ('3Mbps', 'mid') is not available, waiting (12/15s) [0m[K
2022-07-23 15:38:04 [33m[fc2 87864958] Requested quality ('3Mbps', 'mid') is not available, waiting (13/15s) [0m[K
2022-07-23 15:38:06 [33m[fc2 87864958] Requested quality ('3Mbps', 'mid') is not available, waiting (15/15s) [0m[K
2022-07-23 15:38:07 [33m[fc2 87864958] Timeout reached, falling back to next best quality ('1.2Mbps', 'mid') [0m[K
2022-07-23 15:38:07 [fc2 87864958] Received HLS info [0m[K
2022-07-23 15:38:07 [fc2 87864958] Writing stream to 2022-07-23 【ドキドキ!!人生２回目の…】牛タンちゃん22歳ち●ぽを夢中で求め続けた絶対に誰にも言えない夕方 (牛タンちゃん(色白すべすべむっつり)).ts [0m[K
2022-07-23 15:45:17 [31m[fc2 87864958] Server disconnected: 4101 (Paid program) [0m[K
2022-07-23 15:45:17 [fc2 87864958] Remuxing stream to 2022-07-23 【ドキドキ!!人生２回目の…】牛タンちゃん22歳ち●ぽを夢中で求め続けた絶対に誰にも言えない夕方 (牛タンちゃん(色白すべすべむっ つり)).mp4 [0m[K
2022-07-23 15:45:17 [31m[main] FileNotFoundError(2, 'The system cannot find the file specified', None, 2, None) [WinError 2] The system cannot find the file specified [0m[K
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000021F5333B5B0>
Traceback (most recent call last):
  File "C:\Users\ROG\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\ROG\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\ROG\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
    self._check_closed()
  File "C:\Users\ROG\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000021F5333B5B0>
Traceback (most recent call last):
  File "C:\Users\ROG\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\ROG\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\ROG\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
    self._check_closed()
  File "C:\Users\ROG\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000021F5333B5B0>
Traceback (most recent call last):
  File "C:\Users\ROG\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\ROG\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\ROG\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
    self._check_closed()
  File "C:\Users\ROG\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by hizkifw** [comment]
Hi, make sure you have `ffmpeg` installed on your system. You can check by running `ffmpeg -version` in your terminal.

If not you can check [this guide](https://github.com/holoArchivists/hollow_memories).

**Comment by erungeis** [comment]
This time i already have ffmpeg installed in my system

C:\Users\ROG>fc2-live-dl https://live.fc2.com/40495362/
2022-07-26 12:49:46 [main] fc2-live-dl v2.1.1 [0m[K
2022-07-26 12:49:46 [fc2 40495362] Fetching stream info [0m[K
2022-07-26 12:49:48 [fc2 40495362] Found websocket url [0m[K
2022-07-26 12:49:49 [33m[fc2 40495362] Requested quality ('3Mbps', 'mid') is not available, waiting (0/15s) [0m[K
2022-07-26 12:49:51 [33m[fc2 40495362] Requested quality ('3Mbps', 'mid') is not available, waiting (2/15s) [0m[K
2022-07-26 12:49:52 [33m[fc2 40495362] Requested quality ('3Mbps', 'mid') is not available, waiting (3/15s) [0m[K
2022-07-26 12:49:53 [33m[fc2 40495362] Requested quality ('3Mbps', 'mid') is not available, waiting (4/15s) [0m[K
2022-07-26 12:49:54 [33m[fc2 40495362] Requested quality ('3Mbps', 'mid') is not available, waiting (5/15s) [0m[K
2022-07-26 12:49:55 [33m[fc2 40495362] Requested quality ('3Mbps', 'mid') is not available, waiting (7/15s) [0m[K
2022-07-26 12:49:57 [33m[fc2 40495362] Requested quality ('3Mbps', 'mid') is not available, waiting (8/15s) [0m[K
2022-07-26 12:49:58 [33m[fc2 40495362] Requested quality ('3Mbps', 'mid') is not available, waiting (9/15s) [0m[K
2022-07-26 12:49:59 [33m[fc2 40495362] Requested quality ('3Mbps', 'mid') is not available, waiting (10/15s) [0m[K
2022-07-26 12:50:00 [33m[fc2 40495362] Requested quality ('3Mbps', 'mid') is not available, waiting (11/15s) [0m[K
2022-07-26 12:50:02 [33m[fc2 40495362] Requested quality ('3Mbps', 'mid') is not available, waiting (13/15s) [0m[K
2022-07-26 12:50:03 [33m[fc2 40495362] Requested quality ('3Mbps', 'mid') is not available, waiting (14/15s) [0m[K
2022-07-26 12:50:04 [33m[fc2 40495362] Requested quality ('3Mbps', 'mid') is not available, waiting (15/15s) [0m[K
2022-07-26 12:50:05 [33m[fc2 40495362] Timeout reached, falling back to next best quality ('2Mbps', 'mid') [0m[K
2022-07-26 12:50:05 [fc2 40495362] Received HLS info [0m[K
2022-07-26 12:50:05 [fc2 40495362] Writing stream to 2022-07-26 ♡生配信 (あい♡).ts [0m[K
2022-07-26 13:09:20 [31m[fc2 40495362] Server disconnected: 4101 (Paid program) [0m[K
2022-07-26 13:09:20 [fc2 40495362] Remuxing stream to 2022-07-26 ♡生配信 (あい♡).mp4 [0m[K
2022-07-26 13:09:23 [fc2 40495362] Removing intermediate files [0m[K
2022-07-26 13:09:23 [fc2 40495362] Done [0m[K
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001F8438AB5B0>
Traceback (most recent call last):
  File "C:\Users\ROG\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\ROG\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\ROG\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
    self._check_closed()
  File "C:\Users\ROG\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001F8438AB5B0>
Traceback (most recent call last):
  File "C:\Users\ROG\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\ROG\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\ROG\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
    self._check_closed()
  File "C:\Users\ROG\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by hizkifw** [comment]
Looks like it's finished recording successfully, it just crashes when exiting. Related: https://github.com/aio-libs/aiohttp/issues/4324.

Can you try running this version and see if the error still happens?
- Download [this zip](https://github.com/HoloArchivists/fc2-live-dl/archive/refs/heads/fix/aiohttp-windows.zip)
- Extract it somewhere, open your Command Prompt / Powershell in that folder
- Run `python -m fc2_live_dl https://...`

**Comment by erungeis** [comment]
Thanks for the help, it's working now

C:\Users\ROG\Documents\fc2-live-dl-fix-aiohttp-windows>python -m fc2_live_dl https://live.fc2.com/24116510/
2022-07-27 09:31:40 [main] fc2-live-dl v2.1.1 [0m[K
2022-07-27 09:31:40 [fc2 24116510] Fetching stream info [0m[K
2022-07-27 09:31:42 [fc2 24116510] Found websocket url [0m[K
2022-07-27 09:31:43 [fc2 24116510] Received HLS info [0m[K
2022-07-27 09:31:43 [fc2 24116510] Writing stream to 2022-07-27 ナニしちゃおっかな(_・ω・)_ (くるみ୨୧生配信).ts [0m[K
2022-07-27 09:32:54 [31m[fc2 24116510] Server disconnected: 4101 (Paid program) [0m[K
2022-07-27 09:32:54 [fc2 24116510] Remuxing stream to 2022-07-27 ナニしちゃおっかな(_・ω・)_ (くるみ୨୧生配信).mp4 [0m[K
2022-07-27 09:32:55 [fc2 24116510] Removing intermediate files [0m[K
2022-07-27 09:32:55 [fc2 24116510] Done [0m[K

**Comment by hizkifw** [comment]
Good to hear!
