### ISSUE TITLE
ConnectionResetError: [WinError 10054]

### ISSUE THREAD

**Issue by Kaiay** [HoloArchivists/fc2-live-dl#43]
> Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
> handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
> Traceback (most recent call last):
>   File "C:\Users\andyw\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
>     self._context.run(self._callback, *self._args)
>   File "C:\Users\andyw\AppData\Local\Programs\Python\Python311\Lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
>     self._sock.shutdown(socket.SHUT_RDWR)
> ConnectionResetError: [WinError 10054] 遠端主機已強制關閉一個現存的連線。

recently got this error. Am I set some wrong that make the server stop me because I request too fast?

Python 3.11.2
fc2-live-dl v2.1.3
command to run:
```
cd /d H:\NS\Sound\tools
autofc2 --config autofc2.json
```
autofc2.json
```
{
  "default_params": {
    "quality": "3Mbps",
    "latency": "mid",
    "threads": 4,
    "outtmpl": "%(channel_name)s/%(date)s %(title)s.%(ext)s",
    "write_chat": false,
    "write_info_json": false,
    "write_thumbnail": false,
    "wait_for_live": true,
	"wait_for_quality_timeout": 45,
    "wait_poll_interval": 10,
    "cookies_file": null,
    "remux": true,
    "keep_intermediates": false,
    "extract_audio": false
  },
  "channels": {
    "40740626":{},
    "72364867":{},
    "81840800":{},
    "91544481":{},
    "84683124":{},
    "27043183":{},
    "75399790":{},
    "38231874":{},
    "41958478":{},
    "85995227":{},
    "37030653":{},
    "74113179":{}
  }
}
```

**Comment by Kaiay** [comment]
Oh seems it's problem on my side. Will check the connection.
