### ISSUE TITLE
Downloads wont start 

### ISSUE THREAD

**Issue by leonmcfly** [HoloArchivists/fc2-live-dl#46]
```
Task exception was never retrieved
future: <Task finished name='Task-162' coro=<AutoFC2.handle_channel() done, defined at C:\Users\leonm\AppData\Local\Programs\Python\Python311\Lib\site-packages\fc2_live_dl\autofc2.py:116> exception=<InvalidURL >>
Traceback (most recent call last):
  File "C:\Users\leonm\AppData\Local\Programs\Python\Python311\Lib\site-packages\fc2_live_dl\autofc2.py", line 119, in handle_channel
    await fc2.download(channel_id)
  File "C:\Users\leonm\AppData\Local\Programs\Python\Python311\Lib\site-packages\fc2_live_dl\FC2LiveDL.py", line 175, in download
    async with self._session.get(thumb_url) as resp:
  File "C:\Users\leonm\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "C:\Users\leonm\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\client.py", line 508, in _request
    req = self._request_class(
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\leonm\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\client_reqrep.py", line 305, in __init__
    self.update_host(url)
  File "C:\Users\leonm\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\client_reqrep.py", line 364, in update_host
    raise InvalidURL(url)
aiohttp.client_exceptions.InvalidURL
```

after starting the command autofc2 --config autofc2.json and a stream is found it will just loop through this and wont start anything.
Python version: 3.11
fc2-live-dl version: 2.2.0

**Comment by leonmcfly** [comment]
The URL did work the last time just today it wont work

**Comment by leonmcfly** [comment]
is it possible that the error happens because it tries to get the .png but there is no png and so it fails?

**Comment by hizkifw** [comment]
Seems to be an issue downloading thumbnails, you can disable it for now while I work on a fix. Set `write_thumbnail` to `false`

**Comment by leonmcfly** [comment]
ok thx
